# Setup
title:        Mohammed GitHub
tagline:      Web interface for my repositories
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Mohammed Abdelgadir
  url:        https://www.linkedin.com/in/weekmo

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman